### ISSUE TITLE
Creating a file with an invalid file extension causes the app to break

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotGames/Quartz#10]
Creating a file with an invalid file extension causes the app to break

Expected result:
Either the app says it's invalid or it opens

Observed:  
The app's UI disappears
![image](https://github.com/DoubleDotGames/Quartz/assets/96972638/b4bae518-00c3-440a-a68e-1f50e24e3259)

**Comment by DoubleDotGames** [comment]
I'm currently looking into the issue. A fix should roll out with v1.0.2
